PROGS_COUNTDOWNTIMER_OBJS := countdowntimer.o
PROGS_COUNTDOWNTIMER_OBJS := $(PROGS_COUNTDOWNTIMER_OBJS:%=$(TDIR)/countdowntimer/%)
ALL_OBJS += $(PROGS_COUNTDOWNTIMER_OBJS)

$(TDIR)/bin/countdowntimer : $(TSTART) $(PROGS_COUNTDOWNTIMER_OBJS) $(TLIBC)